### ISSUE TITLE
定时框架（Timer和Quartz）

### ISSUE THREAD

**Issue by steven-wan** [steven-wan/StudyBookNote#63]
> 因为工作中会遇到需要定时处理的问题，所有不可避免的需要学习和了解定时相关的框架，这里主要是讲 Java 自带的定时任务处理（Timer，ScheduledThreadPoolExecutor），以及常用的开源框架 **Quartz**。

### 1.1 特性
  > 它是 java.util 包有关任务处理类，特征就是每一个 Timer 对象，背后都是一个独立线程。
  - 一个线程
  - 所有任务的执行顺序都是串行的，由唯一的线程去执行
  - schedule 方法的三个参数：TimerTask task, Date firstTime, long period
  - task：定时任务，继承它就可以。
  - firstTime：执行时间，一般就是第一次执行的时间。
  - period：**当为0时**：代表改任务**只执行一次**，**当大于0时**：代表任务**重复执行**，每次任务的**执行时间间隔以 period 毫秒为单位**
  - 如果想终止执行的任务，调用 cancel 方法。
  - 当一下子有多个并发任务时，在内部，它会以 binary heap to represent its task queue 。
  - 它内部其实就是 queue 通过 wait() 和 notify()
    
  ### 1.2 缺点
  - 它不保证真正的执行时间，因为串性执行，当一个任务耗用太多时间后，后续任务会相对应的延迟，而且会在耗时任务执行完后，马上立刻执行那些被耽误的任务。
  - 单线程，效率不高。
  - 时间规则不方便，比如我想要每月的20号执行。

### 3.1 特性
  >相较于前面的几个，它的优势在于：灵活和复杂的定时任务，它有更多的触发器去满足你的业务需求，第二个就是集群，以及灾难转移（负债均衡等等）
  ### 3.2 快速的开始一个 quartz
  - #### 3.2.1 quartz.properties 配置，它有一个默认的配置，如果你想配置自己的东西，需要在你的资源目录下面创建一个同名的去覆盖默认的。它有三个非常重要的模块需要配置：ThreadPool，JobStore ，Scheduler 
     - #### 3.2.1.1 ThreadPool：它最重要的是class，threadCount，threadPriority，threadsInheritContextClassLoaderOfInitializingThread。一般 class，threadsInheritContextClassLoaderOfInitializingThread 都可以抄默认的就可以，一般主动修改的都是 threadCount，threadPriority，改动最多的就是 threadCount。顾名思义就是工作线程总量
     - #### 3.2.1.1 JobStore：它有三个划分：RAMJobStore，StdJDBCDelegate,TerracottaJobStore
     RAMJobStore：就是把 job 和 trigger 的数据存储内存，速度快，但是项目重启数据就会丢失。
     
     StdJDBCDelegate：就是把 job 和 trigger 的数据存储在数据库中，当然也有根据数据库对应的，比如MYSQLJDBCDelegate,一般用这个就可以了，速度慢，但是项目重启数据会从数据库中加载回来，不会丢失。对应的，系统它会生成一系列的表。
     - #### 3.2.1.2 jobStore 它还需要几个注意点：table_prefix,和 dataSource ，以及 jobStore.class，useProperties 。
     table_prefix：就是系统默认生成的表前缀，一般是默认的 QUARTZ_
     dataSource: 可以沿用项目已经有的 dataSource，也可以用单独配置，单独配置需要注意的就是：当你指定了 dataSource 的名称后（比如 Mydb），后续的 org.quartz.dataSource.NAME.driver 中的 NAME 就是你之前指定的(Mydb)，还有注意点：**尽量数据库的连接数大于你的工作线程数量（+2）**
     jobStore.class:org.quartz.impl.jdbcjobstore.JobStoreTX,org.quartz.impl.jdbcjobstore.JobStoreCMT  它们的最大区别就是一个是你应用的事务管理，另一个是当你需要其他事务参与，或者说把事务交给全局的服务器管理。一般默认的是 JobStoreTX
     useProperties：它代表 dataMap 和存储到数据库的类型都是 String 类型，这样可以避免序列化以及复杂的对象化存储时遇到的各种问题。
     
     - #### 3.2.1.1 Scheduler：StdSchedulerFactory，DirectSchedulerFactory 建议使用前者，后者过于复杂。
     instanceName ： Scheduler 的名称，注意如果是集群，这个需要其他节点名称一致
     instanceId：AUTO，就可以了，集群中每个节点唯一
     wrapJobExecutionInUserTransaction：是否在 JOB 执行前加上事务，看个人的事务需要
quartz.properties:
```
#scheduler
org.quartz.scheduler.instanceName: DefaultQuartzScheduler
org.quartz.scheduler.rmi.export: false
org.quartz.scheduler.rmi.proxy: false
org.quartz.scheduler.wrapJobExecutionInUserTransaction: false
#threadPool
org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount: 10
org.quartz.threadPool.threadPriority: 5
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
#threadPool
org.quartz.jobStore.misfireThreshold: 60000
org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
org.quartz.jobStore.useProperties: true
```
spring boot quartz 的相关配置:
```
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ip/xxx?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: xx
    password: xxx
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyQuartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 3
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
```
schedule 启动：
```
        Scheduler defaultScheduler = StdSchedulerFactory.getDefaultScheduler();
        defaultScheduler.start();
        defaultScheduler.shutdown();
```

  ### 3.3 深入了解 quartz 的各个模块的细节以及注意事项
  > 在3.2中，通过上面的配置你就可以快速启动一个模块 schedule，根据日志你就可以看到对应的输出了，比如线程数量等等。但是启动了调度器 schedule，之后，我们需要给他创建任务和触发器，下面就是需要重点介绍的三个模块中的后面两个：job，trigger 
  -   #### 3.3.1 job ：就是具体的任务实现，你只需要实现这个接口，它里面只有一个方法，
      - #### 3.3.1.1 Job 和 JobDetail 区别与联系
      每一个 Job 针对 Schedule 而言都是唯一的，而 Job 只是一个接口，唯一的方法，没有属性，JobDetail 就是一个给 Job 实现类提供属性的，而且有 JobDataMap 传递参数的类。JobDetail 是对 Job 的定义。
      - #### 3.3.1.2 每一次触发器触发，调用工作，都是会重新创建一个实例对象，这个意味着，实例变量是没有用的，再每次调用都是新的，旧的会被垃圾回收。当一些状态或者参数需要在这些实例中传递时怎么解决？这个问题就是后续为什么需要 jobDataMap 的原因。
      - #### 3.3.1.3 @DisallowConcurrentExecution 和 @PersistJobDataAfterExecution 它们一般都是一起使用的，注解在 job 实现类中。它们代表了 job 实例每次只能有一个工作，不能并发，而且在 job 实例执行完成后，马上更新 schedule 中的 jobDataMap 中的数据，避免其他线程拿的还是旧的数据。
      - #### 3.3.1.4 Durability 和 RequestsRecovery 前者如果一个 job 不是持久的，当没有绑定触发器就会被删除，后者就是当 schedule 意外停止后，导致 job 没有执行完成，那么当它是 true 时，在 schedule 启动时，它会重新启动该任务。
      - #### 3.3.1.4 JobDetail 和 Job 的创建
    JobDetail 由 JobBuilder 创建，例子如下：
```
 JobDetail jobDetail = newJob(HelloJob.class).withIdentity("job1", "group1").build();
```

```
public class HelloJob implements Job {
    @Override
    protected void executeInternal(JobExecutionContext jobExecutionContext) throws JobExecutionException {
        System.out.println("test quartz ");
    }
}
```
  - #### 3.3.2 jobDataMap  
    - #### 3.3.2.1 它出现的原因就是解决 job 实例，trigger 中传递参数。 
    - #### 3.3.2.2 它是存储在 schedule 中的，job 和 trigger 它们都是独立的，如果 job 和 trigger 刚好有相同的 key，如果通过彼此的实例调用 key，是没有问题的，但是当调用 getMergedJobDataMap() 方法后，后者 key 的值会覆盖前者的值
    - #### 3.3.2.3 当你在 job 或者 trigger 中设置了 jobDataMap ，那么在 job 中就可以设置对应的属性，同时包含对应的 set 方法，这样就可以直接取 jobDataMap 中对应的值了，而不是再次通过 jobExecutionContext 去获取。原因就是 JobFactory 在创建 job 实例时，会把 scheduler 的 jobDataMap 的值去给 job 中的实例属性对比并赋值。
    
  -   #### 3.3.3 trigger 主要使用多的是两个 simpleTrigger 和 CronTrigger。它们需要关注的其实就是三个特点：起始时间，截止时间，以及 misfire 后怎么执行。不同的 trigger 有不同的，具体根据特点的分析
      - #### 3.3.3.1  startTime （起始时间）：如果没有选择，默认的就是现在开始
      - #### 3.3.3.2  endTime（截止时间） ：如果指定了截止时间，执行次数没有到位的那种也会停止。
      - #### 3.3.3.3  MISFIRE_INSTRUCTION_SMART_POLICY 默认的 misfire 机制。updateAfterMisfire() 该方法会更新各自的策略。所以具体的触发器看自己的这个方法
      - #### 3.3.3.4 simpleTrigger 和 CronTrigger。 
        - #### 3.3.3.4.1 simpleTrigger ：特定时间内，延迟一定时间，重复 n 次的触发器
            - #### 3.3.3.4.1.1 ISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY：顾名思义，忽视它
            - #### 3.3.3.4.1.2 MISFIRE_INSTRUCTION_FIRE_NOW：立刻执行
            - #### 3.3.3.4.1.3 MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT：立刻现在执行，比如一共 6 次，错过了一次，那还是需要 5次
            - #### 3.3.3.4.1.4 MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT：立刻现在执行，比如一共 6 次，错过了一次，那还是只需要执行剩下的 4次
            - #### 3.3.3.4.1.5 MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT：等待下次触发，比如一共 6 次，错过了一次，那还是只需要执行剩下的 4次
            - #### 3.3.3.4.1.6 MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT：等待下次触发，比如一共 6 次，错过了一次，那还是需要 5次
      
        - #### 3.3.3.4.2 CronTrigger：它针对那些日历，比如每个月的星期四中午十二点二点三分，重复几次这些复杂的，特点的触发器。比如："0 15 10 ? * 6#3"。一般 CronExpression 表达式在线去试下，也不怎么记得住。
          - #### 3.3.3.4.2.1 MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY：无视
          - #### 3.3.3.4.2.2 MISFIRE_INSTRUCTION_DO_NOTHING：等待下次触发
          - #### 3.3.3.4.2.3 MISFIRE_INSTRUCTION_FIRE_NOW：现在立刻触发
          
  -   #### 3.3.4  监听 Listeners 它主要是三个 TriggerListeners ，JobListeners 和  SchedulerListeners 它们触发的条件看对应的接口就知道了，如果你想要自己的只需要实现它就可以了。主要你可以写特点任务的接口监听器，也可以是全部的接口监听器
```
scheduler.getListenerManager()
.addJobListener(myJobListener, 
KeyMatcher.jobKeyEquals(new JobKey("myJobName", "myJobGroup")));

scheduler.getListenerManager().addSchedulerListener(mySchedListener);
```

  -   #### 3.3.3 trigger 的状状态变更？
